### ISSUE TITLE
404 Error not found

### ISSUE THREAD

**Issue by saidihasan** [twtrubiks/line-bot-tutorial#1]
yo, dude i cant speak china by the way.
i have follow your tutorial how to make bot line.
but i got Error 404 and BOT in line not working.
im pretty sure use the TOKEN correctly from my basic information
could you please help me ? thanks

**Comment by twtrubiks** [comment]
Hello ~
Can you attach your code  ?
or image ? thanks

**Comment by saidihasan** [comment]
![1](https://cloud.githubusercontent.com/assets/10250394/22696234/d9a489c0-ed7f-11e6-853e-a3b97efe1165.jpg)

now i got error 400, and my bot still not working.
my bot give message : 
[Oops!]
To use this service, you must allow the service's provider to access your info

**Comment by twtrubiks** [comment]
You posted the website is my !!!

Please post your own!!

**Comment by saidihasan** [comment]
okay dude, im so sorry. i got wrong screenshoot to upload. 
the webhook return "Success" for now.
but, the problem now is the bot in the line.
like this.
![screenshot_2017-02-08-14-54-53](https://cloud.githubusercontent.com/assets/10250394/22728785/59a8fa1a-ee12-11e6-9fe7-ba2e9f238c5a.png)

**Comment by twtrubiks** [comment]
click Approval screen.  permit it .

**Comment by saidihasan** [comment]
i cant click that message bro, it doesnt pop anything.

**Comment by twtrubiks** [comment]
Plus friends, line should ask you permission, you can choose to agree

Approval screen  should be able to press

**Comment by saidihasan** [comment]
@twtrubiks thank you dude, finally i solve my problem.
sorry distrubing your time.

the problem is my Line App doesnt Up To Date, i must to update it. gg

**Comment by twtrubiks** [comment]
ok
