### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by EggyCheng** [twtrubiks/line-bot-tutorial#3]
在驗證的時候出現此error是因為line manager那邊發出驗證的request是一個假訊息
所以建議是還在做驗證動作的時候先把範例code的handle_message(event) function中的code都先註掉
改print "helloworld" 之類的 再驗證

by the way, 你的文章寫得很好! 感謝

**Comment by twtrubiks** [comment]
非常謝謝你，我會再把你的說明更新到 README 裡面^^

**Comment by Eric9453** [comment]
> 在驗證的時候出現此error是因為line manager那邊發出驗證的request是一個假訊息 所以建議是還在做驗證動作的時候先把範例code的handle_message(event) function中的code都先註掉 改print "helloworld" 之類的 再驗證
> 
> by the way, 你的文章寫得很好! 感謝

感謝你的經驗談，最近在開發linebot的相關應用有遇到了類似的情況
照正常程序debug的話一時間還真不知哪邊出錯
此建議省了不少時間
