### ISSUE TITLE
回報一個小問題(imgur抓圖)

### ISSUE THREAD

**Issue by yiyu0x** [twtrubiks/line-bot-tutorial#7]
原本因為imgur API傳回來的圖是http開頭
所以要字串取代變https  
但是今天早上測試發現傳回來的圖變成https開頭
所以字串取代完變成httpss --> 網址失效

比較萬全的方法應該要檢查網址是否為https開頭 
不是的話才進行取代

**Comment by twtrubiks** [comment]
@yiyu0chang 非常謝謝您的回報，已經修正完畢，commit id [dbe67a0cf31742e4c](https://github.com/twtrubiks/line-bot-tutorial/commit/dbe67a0cf31742e4c08367118520d98ebcbd13ec)

**Comment by abccbaandy** [comment]
小建議，issue解完可以在commit message打`fix issue number`
比如要關閉這個issue就寫`fix #7`

詳細語法可以參考[這篇](https://help.github.com/articles/closing-issues-using-keywords/)

**Comment by yiyu0x** [comment]
謝謝你~~

馬上閱讀一下👍

**Comment by twtrubiks** [comment]
@abccbaandy 謝謝你，我忘記關了XDDD
